flake: remove epoch
It was renamed to edition:

https://github.com/NixOS/rfcs/commit/cc5d0a24970a49d7da294544aff2fb3c26139635

leading to the following error:

error: flake 'git+file:///home/jtojnar/Projects/nixflk?ref=template&rev=31c2b767ca7cb901040e388794b34942807719e0' has an unsupported attribute 'epoch', at /nix/store/yndrc91vlh5vm0k4nngx303q1cjm77z9-source/flake.nix:4:3

but that itself has been deprecated:

warning: flake 'git+file:///home/jtojnar/Projects/nixflk' has deprecated attribute 'edition'